### PR TITLE
feat: [sc-117417] Add semver support and device-os-output variable

### PR DESCRIPTION
**Pull request by laupow**
Story details: https://app.shortcut.com/particle/story/117417

Adds `device-os-version` output. When users pass a semver or `latest` as the `device-os-version` input, it may be useful to know which Device OS version the firmware was compiled against.

### CODE REVIEW

**Comment by wraithan** [comment]
Latest would be good to have, but I wanted *latest LTS* if it is available. What about enabling something like this [tilde range syntax](https://github.com/npm/node-semver#tilde-ranges-123-12-1) then we can just say `~2.2` which would say "give me the latest 2.x and at minimum 2.2"? This is more like what I'd expect from a version specifier.

**Comment by laupow** [comment]
@wraithan The PR now adds support for semver device-os-version inputs.

How does the usage docs look?
https://github.com/particle-iot/compile-action/blob/0f369757854bc98034a9afa75b1d0b922f4b29a8/README.md?plain=1#L20-L28

**Comment by wraithan** [comment]
> @wraithan The PR now adds support for semver device-os-version inputs.
> 
> How do the usage docs look for your use-case? Tilde versions are supported but not documented.

Carrot ranges are good too, they're default in npm for a reason. Works for me, looks like the build fails when `latest-lts` can't find an LTS version, that works for me. Wonder if we should document that or if it would be too verbose/discourage use. 

The note about production is also interesting, our users do not use our platform that way, they definitely hardcode a version and leave it forever in most cases, which they can do by omiting the carrot so it's fine. Upgrades within a major, especially if the device has kept up on OS versions will (on 2.x+) be combined OTA as well as having incremental. So in many cases can skip safe mode so it feels like it'd be fine to suggest using a semver range in production, but the more risk adverse or those burned by safe mode healer + bad connectivity in the past will almost certainly hardcode an OS version.

**Review by wraithan — APPROVED** [review]

**Comment by wraithan** [comment]
I appreciate how well tested all this code is, I was able to scroll through the tests and see how things would react, very nice.

**Pull request merged**
